name: Run Azure Login with OIDC

on: 
  push:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - identity/oidc/token/role-001
      - id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.shutthegoatup.com
          method: jwt
          role: robot
          secrets: |
            /identity/oidc/token/role-001 token | VAULT_JWT ;  
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az login --service-principa -u ${{ secrets.AZURE_CLIENT_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }} --federated-token ${{ steps.secrets.outputs.VAULT_JWT }}
            az account show